theme = "autumn"
transparent_background = true

[themes.autumn]
base = "github-dark-default"
label = "Autumn"
background = "#232323"
panel = "#232323"
panelAlt = "#212121"
border = "#404040"
accent = "#86c1b9"
accentMuted = "#72a59e"
text = "#F3F2CC"
muted = "#c8c8c8"
lineNumberBg = "#232323"
lineNumberFg = "#404040"
selectedHunk = "#404040"
addedSignColor = "#99be70"
removedSignColor = "#F05E48"
badgeAdded = "#99be70"
badgeRemoved = "#F05E48"
badgeNeutral = "#c8c8c8"
fileNew = "#99be70"
fileDeleted = "#F05E48"
fileRenamed = "#cfba8b"
fileModified = "#FAD566"
fileUntracked = "#72a59e"
noteBorder = "#cfba8b"
noteTitleText = "#F3F2CC"

[themes.autumn.syntax_scopes]
"comment" = "#72a59e"
"string" = "#99be70"
"keyword" = "#F05E48"
"constant" = "#FAD566"
"entity.name.function" = "#86c1b9"
"entity.name.type" = "#cfba8b"
"keyword.operator" = "#86c1b9"
"punctuation" = "#c8c8c8"
