theme = "vague"
transparent_background = true

[themes.vague]
base = "github-dark-default"
label = "Vague"
background = "#141415"
panel = "#141415"
panelAlt = "#252530"
border = "#606079"
accent = "#8ba9c1"
accentMuted = "#6e94b2"
text = "#cdcdcd"
muted = "#aeaed1"
lineNumberBg = "#141415"
lineNumberFg = "#606079"
selectedHunk = "#252530"
addedSignColor = "#7fa563"
removedSignColor = "#d8647e"
badgeAdded = "#7fa563"
badgeRemoved = "#d8647e"
badgeNeutral = "#aeaed1"
fileNew = "#99b782"
fileDeleted = "#e08398"
fileRenamed = "#bb9dbd"
fileModified = "#f3be7c"
fileUntracked = "#8ba9c1"
noteBorder = "#6e94b2"
noteBackground = "#141415"
noteTitleBackground = "#252530"
noteTitleText = "#cdcdcd"

[themes.vague.syntax_scopes]
"comment" = "#aeaed1"
"string" = "#99b782"
"keyword" = "#d8647e"
"constant" = "#f3be7c"
"entity.name.function" = "#8ba9c1"
"entity.name.type" = "#bb9dbd"
"keyword.operator" = "#6e94b2"
"variable" = "#cdcdcd"
"punctuation" = "#aeaed1"
